Implement RemoveAll in PsDataArrayProxy
PushkinStudio/PsData pull request #8
Opened 2019-07-02 10:52 UTC by Antonrr

2019-07-02 11:36 UTC, nprudnikov requested changes

2019-07-02 11:36 UTC, nnprudnikov commented on Source/PsDataPlugin/Classes/Collection/PsDataArrayProxy.h
> +			if (Predicate(*It))
We can change the element in the predicate, please use const for the argument

2019-07-02 11:51 UTC, nprudnikov requested changes

2019-07-02 11:51 UTC, nnprudnikov commented on Source/PsDataPlugin/Classes/Collection/PsDataArrayProxy.h
> +				UPsDataEvent::DispatchChange(Instance.Get(), Field);
Use `UPsDataEvent::DispatchChange(Instance.Get(), Field);` once after loop
For example:
```
 if (RemovedElements > 0)
{
 UPsDataEvent::DispatchChange(Instance.Get(), Field);
}
```

2019-07-02 14:21 UTC, merged

2019-07-03 11:59 UTC, ufna reviewed
good